import { NextResponse } from "next/server";
import { loadDB, loadDocData } from "@/lib/db";
import { getUserFromRequest } from "@/lib/auth";
import { generateExcel } from "@/lib/excel";
import ExcelJS from "exceljs";
import { analyzeRedFlags } from "@/lib/redflags";

// POST body: { ids: [1, 2, 3] } — combine up to 5 docs into one Excel
export async function POST(request) {
  const payload = await getUserFromRequest(request);
  if (!payload) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { ids } = await request.json();
  if (!ids?.length || ids.length > 5) {
    return NextResponse.json({ error: "Provide 1-5 document IDs" }, { status: 400 });
  }

  const db = await loadDB();
  const docMetas = ids
    .map(id => db.documents.find(d => d.id === Number(id) && d.organization_id === payload.orgId))
    .filter(d => d && d.status === "completed");

  if (docMetas.length === 0) {
    return NextResponse.json({ error: "No completed documents found" }, { status: 404 });
  }

  // Load extracted_data for each doc in parallel
  const extractedList = await Promise.all(docMetas.map(d => loadDocData(d.id)));
  const docs = docMetas
    .map((d, i) => ({ ...d, extracted_data: extractedList[i] }))
    .filter(d => d.extracted_data);

  if (docs.length === 0) {
    return NextResponse.json({ error: "No documents with extracted data found" }, { status: 404 });
  }

  // Build combined workbook
  const wb = new ExcelJS.Workbook();
  wb.creator = "DataCrunch";
  wb.created = new Date();

  const NAVY = "FF1B2A4A", GREEN = "FF3DAA5C", RED = "FFC0392B", WHITE = "FFFFFFFF", LIGHT = "FFF5F7FA";

  function hdr(ws, row, col, value) {
    const c = ws.getCell(row, col);
    c.value = value;
    c.font = { name: "Calibri", bold: true, color: { argb: WHITE }, size: 11 };
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
    c.alignment = { horizontal: "center", vertical: "middle" };
  }
  function cl(ws, row, col, value, opts = {}) {
    const c = ws.getCell(row, col);
    c.value = value;
    c.font = { name: "Calibri", bold: opts.bold, color: { argb: opts.color || "FF000000" }, size: opts.size || 10 };
    if (opts.bg) c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: opts.bg } };
    c.alignment = { horizontal: opts.align || (typeof value === "number" ? "right" : "left"), vertical: "middle", wrapText: opts.wrap };
    if (opts.numFmt) c.numFmt = opts.numFmt;
  }

  // Cover sheet
  const cover = wb.addWorksheet("Overview");
  cover.views = [{ showGridLines: false }];
  cover.mergeCells(1, 1, 1, 5);
  const t = cover.getCell(1, 1);
  t.value = "DataCrunch — Combined Due Diligence Report";
  t.font = { name: "Calibri", bold: true, size: 18, color: { argb: WHITE } };
  t.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
  t.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
  cover.getRow(1).height = 40;

  cover.mergeCells(2, 1, 2, 5);
  const s = cover.getCell(2, 1);
  s.value = `Generated by DataCrunch | ${new Date().toLocaleDateString("fr-FR")} | ${docs.length} document(s)`;
  s.font = { name: "Calibri", size: 10, italic: true, color: { argb: NAVY } };
  s.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEEF2F7" } };
  s.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
  cover.getRow(2).height = 20;
  cover.getRow(3).height = 10;

  ["#", "Document", "Type", "Period", "Risk Grade"].forEach((h, i) => hdr(cover, 4, i + 1, h));
  docs.forEach((doc, i) => {
    const rf = doc.extracted_data._risk || analyzeRedFlags(doc.extracted_data);
    const r = 5 + i;
    const bg = i % 2 === 0 ? LIGHT : WHITE;
    cl(cover, r, 1, i + 1, { bg, align: "center" });
    cl(cover, r, 2, doc.filename, { bg });
    cl(cover, r, 3, doc.document_type?.replace(/_/g, " "), { bg });
    cl(cover, r, 4, doc.extracted_data?.period || "—", { bg });
    cl(cover, r, 5, `${rf.grade} — ${rf.gradeLabel}`, { bg, bold: true, color: "FF" + rf.gradeColor });
    cover.getRow(r).height = 18;
  });
  cover.getColumn(1).width = 4;
  cover.getColumn(2).width = 35;
  cover.getColumn(3).width = 22;
  cover.getColumn(4).width = 20;
  cover.getColumn(5).width = 22;

  // For each doc, generate its individual Excel and copy sheets
  for (const doc of docs) {
    const ext = doc.extracted_data;
    const type = ext.document_type;
    const label = `${type.replace(/_/g, " ")} - ${ext.period || doc.id}`.slice(0, 30);
    const currency = ext.currency || "EUR";
    const fmt = `#,##0 "${currency}"`;

    if (type === "financial_statement") {
      const ws = wb.addWorksheet(label);
      ws.views = [{ showGridLines: false }];
      ws.mergeCells(1, 1, 1, 4);
      const th = ws.getCell(1, 1);
      th.value = `Financial Statement — ${ext.company_name || "N/A"} (${ext.period || "N/A"})`;
      th.font = { name: "Calibri", bold: true, size: 14, color: { argb: WHITE } };
      th.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
      th.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
      ws.getRow(1).height = 30;

      ["Section", "Item", "Amount", "Note"].forEach((h, i) => hdr(ws, 2, i + 1, h));
      let row = 3;
      for (const [name, sec] of [["Revenue", ext.revenue], ["Expenses", ext.expenses], ["Assets", ext.assets], ["Liabilities", ext.liabilities]]) {
        if (!sec?.items?.length) continue;
        ws.mergeCells(row, 1, row, 4);
        const sh = ws.getCell(row, 1);
        sh.value = name.toUpperCase();
        sh.font = { name: "Calibri", bold: true, color: { argb: WHITE }, size: 11 };
        sh.fill = { type: "pattern", pattern: "solid", fgColor: { argb: GREEN } };
        sh.alignment = { horizontal: "left", vertical: "middle", indent: 1 };
        ws.getRow(row).height = 22;
        row++;
        for (const item of sec.items) {
          const bg = row % 2 === 0 ? LIGHT : WHITE;
          cl(ws, row, 1, name, { bg });
          cl(ws, row, 2, item.label, { bg });
          cl(ws, row, 3, item.amount, { bg, numFmt: fmt });
          cl(ws, row, 4, "", { bg });
          row++;
        }
        cl(ws, row, 2, `TOTAL ${name}`, { bold: true, bg: "FFE8F5E9", color: NAVY });
        cl(ws, row, 3, sec.total_calculated, { bold: true, bg: "FFE8F5E9", numFmt: fmt, color: NAVY });
        cl(ws, row, 4, sec.mismatch ? "⚠️ MISMATCH" : "✅ OK", { bg: "FFE8F5E9", color: sec.mismatch ? RED : GREEN });
        row += 2;
      }
      ws.getColumn(1).width = 18; ws.getColumn(2).width = 38; ws.getColumn(3).width = 22; ws.getColumn(4).width = 20;
    }

    if (type === "revenue_list" && ext.clients?.length) {
      const ws = wb.addWorksheet(label);
      ws.views = [{ showGridLines: false }];
      ws.mergeCells(1, 1, 1, 4);
      const th = ws.getCell(1, 1);
      th.value = `Revenue — ${ext.company_name || "N/A"} (${ext.period || "N/A"})`;
      th.font = { name: "Calibri", bold: true, size: 14, color: { argb: WHITE } };
      th.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
      th.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
      ws.getRow(1).height = 30;
      ["Client", "Revenue", "%", "Risk"].forEach((h, i) => hdr(ws, 2, i + 1, h));
      const sorted = [...ext.clients].sort((a, b) => b.revenue - a.revenue);
      const total = ext.total_calculated || 1;
      sorted.forEach((c, i) => {
        const r = 3 + i;
        const pct = (c.revenue / total) * 100;
        const bg = i % 2 === 0 ? LIGHT : WHITE;
        cl(ws, r, 1, c.name, { bg });
        cl(ws, r, 2, c.revenue, { bg, numFmt: fmt });
        cl(ws, r, 3, pct / 100, { bg, numFmt: "0.0%" });
        cl(ws, r, 4, pct > 30 ? "🔴 High" : "🟢 Low", { bg, color: pct > 30 ? RED : "FF000000" });
        ws.getRow(r).height = 18;
      });
      ws.getColumn(1).width = 35; ws.getColumn(2).width = 22; ws.getColumn(3).width = 10; ws.getColumn(4).width = 14;
    }

    if (type === "payroll" && ext.employees?.length) {
      const ws = wb.addWorksheet(label);
      ws.views = [{ showGridLines: false }];
      ws.mergeCells(1, 1, 1, 4);
      const th = ws.getCell(1, 1);
      th.value = `Payroll — ${ext.company_name || "N/A"} (${ext.period || "N/A"})`;
      th.font = { name: "Calibri", bold: true, size: 14, color: { argb: WHITE } };
      th.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
      th.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
      ws.getRow(1).height = 30;
      ["Employee", "Role", "Department", "Gross Salary"].forEach((h, i) => hdr(ws, 2, i + 1, h));
      const sorted = [...ext.employees].sort((a, b) => b.gross_salary - a.gross_salary);
      sorted.forEach((e, i) => {
        const r = 3 + i;
        const bg = i % 2 === 0 ? LIGHT : WHITE;
        cl(ws, r, 1, e.name, { bg });
        cl(ws, r, 2, e.role || "—", { bg });
        cl(ws, r, 3, e.department || "—", { bg });
        cl(ws, r, 4, e.gross_salary, { bg, numFmt: fmt });
        ws.getRow(r).height = 18;
      });
      ws.getColumn(1).width = 30; ws.getColumn(2).width = 25; ws.getColumn(3).width = 22; ws.getColumn(4).width = 22;
    }
  }

  const buffer = await wb.xlsx.writeBuffer();
  return new Response(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="DataCrunch_Combined_Report.xlsx"`,
    },
  });
}
