import ExcelJS from "exceljs";
import { analyzeRedFlags } from "./redflags.js";

const NAVY = "FF1B2A4A";
const GREEN = "FF3DAA5C";
const RED = "FFC0392B";
const WHITE = "FFFFFFFF";
const LIGHT = "FFF5F7FA";
const YELLOW = "FFFFF3CD";
const LIGHT_GREEN = "FFE8F5E9";

function hdr(ws, row, col, value) {
  const c = ws.getCell(row, col);
  c.value = value;
  c.font = { name: "Calibri", bold: true, color: { argb: WHITE }, size: 11 };
  c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
  c.alignment = { horizontal: "center", vertical: "middle" };
}

function cell(ws, row, col, value, opts = {}) {
  const c = ws.getCell(row, col);
  c.value = value;
  c.font = { name: "Calibri", bold: opts.bold, color: { argb: opts.color || "FF000000" }, size: opts.size || 10 };
  if (opts.bg) c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: opts.bg } };
  c.alignment = { horizontal: opts.align || (typeof value === "number" ? "right" : "left"), vertical: "middle", wrapText: opts.wrap };
  if (opts.numFmt) c.numFmt = opts.numFmt;
  if (opts.border) {
    c.border = { top: { style: "thin", color: { argb: "FFDEE2E6" } }, bottom: { style: "thin", color: { argb: "FFDEE2E6" } } };
  }
  return c;
}

function sectionHeader(ws, row, cols, label) {
  ws.mergeCells(row, 1, row, cols);
  const c = ws.getCell(row, 1);
  c.value = label;
  c.font = { name: "Calibri", bold: true, color: { argb: WHITE }, size: 11 };
  c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: GREEN } };
  c.alignment = { horizontal: "left", vertical: "middle", indent: 1 };
  ws.getRow(row).height = 22;
}

function logoHeader(ws, title, subtitle, cols) {
  ws.mergeCells(1, 1, 1, cols);
  const t = ws.getCell(1, 1);
  t.value = `DataCrunch — ${title}`;
  t.font = { name: "Calibri", bold: true, size: 16, color: { argb: WHITE } };
  t.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
  t.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
  ws.getRow(1).height = 36;

  ws.mergeCells(2, 1, 2, cols);
  const s = ws.getCell(2, 1);
  s.value = subtitle;
  s.font = { name: "Calibri", size: 10, italic: true, color: { argb: NAVY } };
  s.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEEF2F7" } };
  s.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
  ws.getRow(2).height = 20;
}

function kpiBox(ws, row, col, label, value, color = NAVY) {
  const lc = ws.getCell(row, col);
  lc.value = label;
  lc.font = { name: "Calibri", bold: true, size: 9, color: { argb: "FF6B7A99" } };
  lc.fill = { type: "pattern", pattern: "solid", fgColor: { argb: LIGHT } };
  lc.alignment = { horizontal: "center", vertical: "bottom" };
  ws.getRow(row).height = 18;

  const vc = ws.getCell(row + 1, col);
  vc.value = value;
  vc.font = { name: "Calibri", bold: true, size: 14, color: { argb: color } };
  vc.fill = { type: "pattern", pattern: "solid", fgColor: { argb: LIGHT } };
  vc.alignment = { horizontal: "center", vertical: "middle" };
  ws.getRow(row + 1).height = 28;
}

function addExecutiveSummary(wb, extracted) {
  const ws = wb.addWorksheet("Executive Summary");
  ws.views = [{ showGridLines: false }];

  const company = extracted.company_name || "N/A";
  const period = extracted.period || "N/A";
  const currency = extracted.currency || "EUR";
  const fmt = `#,##0 "${currency}"`;
  const type = extracted.document_type;

  logoHeader(ws, "Executive Summary", `${company} — ${period} | Generated by DataCrunch`, 6);
  ws.getRow(3).height = 10; // spacer

  if (type === "financial_statement") {
    // KPI boxes row 4-5
    const revenue = extracted.revenue?.total_calculated;
    const expenses = extracted.expenses?.total_calculated;
    const ebitda = extracted.ebitda;
    const netIncome = extracted.net_income;
    const assets = extracted.assets?.total_calculated;
    const liabilities = extracted.liabilities?.total_calculated;
    const ebitdaMargin = revenue && ebitda ? ((ebitda / revenue) * 100).toFixed(1) + "%" : "N/A";
    const netMargin = revenue && netIncome ? ((netIncome / revenue) * 100).toFixed(1) + "%" : "N/A";

    cell(ws, 4, 1, "KEY METRICS", { bold: true, size: 12, color: NAVY, bg: WHITE });
    ws.getRow(4).height = 22;

    // KPI row labels
    ["Total Revenue", "Total Expenses", "EBITDA", "Net Income", "Total Assets", "Net Equity"].forEach((label, i) => {
      cell(ws, 5, i + 1, label, { bold: true, size: 9, color: "FF6B7A99", bg: LIGHT, align: "center" });
    });
    ws.getRow(5).height = 18;

    const equity = (assets || 0) - (liabilities || 0);
    [revenue, expenses, ebitda, netIncome, assets, equity].forEach((val, i) => {
      const color = i === 2 || i === 3 ? GREEN : i === 4 || i === 5 ? NAVY : "FF000000";
      const c = ws.getCell(6, i + 1);
      c.value = val ?? "—";
      c.font = { name: "Calibri", bold: true, size: 13, color: { argb: color } };
      c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: LIGHT } };
      c.alignment = { horizontal: "center", vertical: "middle" };
      if (val != null) c.numFmt = fmt;
    });
    ws.getRow(6).height = 30;

    ws.getRow(7).height = 10; // spacer

    // Margin row
    cell(ws, 8, 1, "EBITDA Margin", { bold: true, size: 9, color: "FF6B7A99", bg: "FFE8F5E9", align: "center" });
    cell(ws, 8, 2, ebitdaMargin, { bold: true, size: 13, color: GREEN, bg: "FFE8F5E9", align: "center" });
    cell(ws, 8, 3, "Net Margin", { bold: true, size: 9, color: "FF6B7A99", bg: "FFE8F5E9", align: "center" });
    cell(ws, 8, 4, netMargin, { bold: true, size: 13, color: GREEN, bg: "FFE8F5E9", align: "center" });
    cell(ws, 8, 5, "Validation", { bold: true, size: 9, color: "FF6B7A99", bg: "FFE8F5E9", align: "center" });
    const hasIssues = extracted.validation_notes?.includes("⚠️");
    cell(ws, 8, 5, "Validation", { bold: true, size: 9, color: "FF6B7A99", bg: "FFE8F5E9", align: "center" });
    cell(ws, 8, 6, hasIssues ? "⚠️ Issues" : "✅ Validated", { bold: true, size: 11, color: hasIssues ? RED : GREEN, bg: "FFE8F5E9", align: "center" });

    // Risk grade
    const rf = analyzeRedFlags(extracted);
    const gradeBg = "FF" + rf.gradeColor;
    cell(ws, 4, 5, "RISK GRADE", { bold: true, size: 9, color: "FF6B7A99", bg: LIGHT, align: "center" });
    cell(ws, 4, 6, `${rf.grade} — ${rf.gradeLabel}`, { bold: true, size: 13, color: gradeBg, bg: LIGHT, align: "center" });
    cell(ws, 5, 5, "Red Flags", { bold: true, size: 9, color: "FF6B7A99", bg: LIGHT, align: "center" });
    cell(ws, 5, 6, rf.flags.length === 0 ? "None" : `${rf.flags.length} flag(s)`, { bold: true, size: 13, color: rf.flags.length ? RED : GREEN, bg: LIGHT, align: "center" });

    ws.getRow(8).height = 26;

    ws.getRow(9).height = 10; // spacer

    // Top revenue items
    if (extracted.revenue?.items?.length) {
      sectionHeader(ws, 10, 6, "TOP REVENUE ITEMS");
      hdr(ws, 11, 1, "Item"); hdr(ws, 11, 2, "Amount"); hdr(ws, 11, 3, "% of Total");
      const sorted = [...extracted.revenue.items].sort((a, b) => b.amount - a.amount).slice(0, 8);
      sorted.forEach((item, i) => {
        const r = 12 + i;
        const bg = i % 2 === 0 ? LIGHT : WHITE;
        cell(ws, r, 1, item.label, { bg });
        cell(ws, r, 2, item.amount, { bg, numFmt: fmt });
        cell(ws, r, 3, revenue ? `${((item.amount / revenue) * 100).toFixed(1)}%` : "—", { bg, align: "right" });
        ws.getRow(r).height = 18;
      });
    }

    for (let c = 1; c <= 6; c++) {
      ws.getColumn(c).width = c === 1 ? 30 : 20;
    }
  } else if (type === "revenue_list") {
    const total = extracted.total_calculated || 0;
    const clientCount = extracted.clients?.length || 0;
    const topClient = extracted.clients?.[0];
    const top5pct = extracted.clients?.length
      ? extracted.clients.slice(0, 5).reduce((s, c) => s + c.revenue, 0) / (total || 1) * 100
      : 0;

    cell(ws, 4, 1, "KEY METRICS", { bold: true, size: 12, color: NAVY });
    ["Total Revenue", "# Clients", "Top Client", "Top 5 Concentration", "Validation"].forEach((label, i) => {
      cell(ws, 5, i + 1, label, { bold: true, size: 9, color: "FF6B7A99", bg: LIGHT, align: "center" });
    });
    ws.getRow(5).height = 18;
    [
      { v: total, f: `#,##0 "${currency}"` },
      { v: clientCount, f: null },
      { v: topClient?.name || "—", f: null },
      { v: top5pct ? `${top5pct.toFixed(1)}%` : "—", f: null },
      { v: extracted.mismatch ? "⚠️ Mismatch" : "✅ OK", f: null },
    ].forEach(({ v, f }, i) => {
      const c = ws.getCell(6, i + 1);
      c.value = v;
      c.font = { name: "Calibri", bold: true, size: 13, color: { argb: i === 4 && extracted.mismatch ? RED : NAVY } };
      c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: LIGHT } };
      c.alignment = { horizontal: "center", vertical: "middle" };
      if (f) c.numFmt = f;
    });
    ws.getRow(6).height = 30;
    for (let c = 1; c <= 5; c++) ws.getColumn(c).width = 25;
  } else if (type === "payroll") {
    const total = extracted.total_gross_calculated || 0;
    const headcount = extracted.headcount || 0;
    const avgSalary = headcount ? total / headcount : 0;
    const depts = extracted.employees?.length
      ? [...new Set(extracted.employees.map(e => e.department).filter(Boolean))].length
      : 0;

    ["Total Payroll", "Headcount", "Avg. Salary", "Departments", "Validation"].forEach((label, i) => {
      cell(ws, 5, i + 1, label, { bold: true, size: 9, color: "FF6B7A99", bg: LIGHT, align: "center" });
    });
    ws.getRow(5).height = 18;
    [
      { v: total, f: `#,##0 "${currency}"` },
      { v: headcount, f: null },
      { v: avgSalary, f: `#,##0 "${currency}"` },
      { v: depts || "—", f: null },
      { v: extracted.mismatch ? "⚠️ Mismatch" : "✅ OK", f: null },
    ].forEach(({ v, f }, i) => {
      const c = ws.getCell(6, i + 1);
      c.value = v;
      c.font = { name: "Calibri", bold: true, size: 13, color: { argb: NAVY } };
      c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: LIGHT } };
      c.alignment = { horizontal: "center", vertical: "middle" };
      if (f) c.numFmt = f;
    });
    ws.getRow(6).height = 30;

    // Warning if no employees were found
    if (!extracted.employees?.length) {
      ws.mergeCells(8, 1, 8, 5);
      const warn = ws.getCell(8, 1);
      warn.value = "⚠️ No employees extracted — check that the PDF contains selectable text (not a scanned image).";
      warn.font = { name: "Calibri", bold: true, size: 11, color: { argb: RED } };
      warn.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFDECEA" } };
      warn.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
      ws.getRow(8).height = 36;
    }

    for (let c = 1; c <= 5; c++) ws.getColumn(c).width = 22;
  }
}

export async function generateExcel(extracted) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "DataCrunch";
  wb.created = new Date();

  const type = extracted.document_type;
  const company = extracted.company_name || "N/A";
  const period = extracted.period || "N/A";
  const currency = extracted.currency || "EUR";
  const fmt = `#,##0.00 "${currency}"`;

  // Executive Summary sheet — always first
  addExecutiveSummary(wb, extracted);

  if (type === "financial_statement") {
    const ws = wb.addWorksheet("Financial Detail");
    ws.views = [{ showGridLines: false }];
    logoHeader(ws, "Financial Statement", `${company} — ${period}`, 4);
    ["Category", "Line Item", "Amount", "Validation"].forEach((h, i) => hdr(ws, 3, i + 1, h));

    let row = 4;
    for (const [name, section] of [
      ["Revenue", extracted.revenue],
      ["Expenses", extracted.expenses],
      ["Assets", extracted.assets],
      ["Liabilities", extracted.liabilities],
    ]) {
      if (!section?.items?.length) continue;
      sectionHeader(ws, row, 4, name.toUpperCase());
      row++;
      for (const item of section.items) {
        const bg = row % 2 === 0 ? LIGHT : WHITE;
        cell(ws, row, 1, name, { bg });
        cell(ws, row, 2, item.label, { bg });
        cell(ws, row, 3, item.amount, { bg, numFmt: fmt });
        cell(ws, row, 4, "", { bg });
        row++;
      }
      const mismatch = section.mismatch && section.total_stated != null;
      const valText = mismatch
        ? `⚠️ MISMATCH: stated=${section.total_stated?.toLocaleString()} calc=${section.total_calculated?.toLocaleString()}`
        : section.total_stated != null ? "✅ Validated" : "— No stated total";
      cell(ws, row, 2, `TOTAL ${name}`, { bold: true, bg: LIGHT_GREEN, color: NAVY });
      cell(ws, row, 3, section.total_calculated, { bold: true, bg: LIGHT_GREEN, numFmt: fmt, color: NAVY });
      cell(ws, row, 4, valText, { bg: mismatch ? "FFFDECEA" : LIGHT_GREEN, color: mismatch ? RED : GREEN, bold: mismatch, wrap: true });
      row += 2;
    }
    if (extracted.ebitda != null) {
      cell(ws, row, 2, "EBITDA", { bold: true, color: GREEN });
      cell(ws, row, 3, extracted.ebitda, { numFmt: fmt, bold: true, color: GREEN });
      row++;
    }
    if (extracted.net_income != null) {
      cell(ws, row, 2, "Net Income", { bold: true });
      cell(ws, row, 3, extracted.net_income, { numFmt: fmt, bold: true });
    }
    ws.getColumn(1).width = 18;
    ws.getColumn(2).width = 40;
    ws.getColumn(3).width = 22;
    ws.getColumn(4).width = 55;

  } else if (type === "revenue_list") {
    const ws = wb.addWorksheet("Revenue per Client");
    ws.views = [{ showGridLines: false }];
    logoHeader(ws, "Revenue per Client", `${company} — ${period}`, 5);
    ["#", "Client", "Revenue", "% Total", "Concentration Risk"].forEach((h, i) => hdr(ws, 3, i + 1, h));
    const total = extracted.total_calculated || 1;
    const sorted = [...(extracted.clients || [])].sort((a, b) => b.revenue - a.revenue);
    sorted.forEach((c, i) => {
      const row = i + 4;
      const bg = i % 2 === 0 ? LIGHT : WHITE;
      const pct = (c.revenue / total) * 100;
      cell(ws, row, 1, i + 1, { bg, align: "center" });
      cell(ws, row, 2, c.name, { bg });
      cell(ws, row, 3, c.revenue, { bg, numFmt: fmt });
      cell(ws, row, 4, pct / 100, { bg, numFmt: '0.0%' });
      cell(ws, row, 5,
        pct > 30 ? "🔴 High risk (>30%)" : pct > 15 ? "🟡 Medium risk (>15%)" : "🟢 Low risk",
        { bg, color: pct > 30 ? RED : "FF000000" }
      );
      ws.getRow(row).height = 18;
    });
    const tr = (sorted.length) + 4;
    cell(ws, tr, 2, "TOTAL", { bold: true, bg: LIGHT_GREEN, color: NAVY });
    cell(ws, tr, 3, extracted.total_calculated, { bold: true, bg: LIGHT_GREEN, numFmt: fmt });
    cell(ws, tr, 5, extracted.mismatch ? "⚠️ MISMATCH" : "✅ Validated", { bold: true, color: extracted.mismatch ? RED : GREEN });
    ws.getColumn(1).width = 6;
    ws.getColumn(2).width = 35;
    ws.getColumn(3).width = 22;
    ws.getColumn(4).width = 12;
    ws.getColumn(5).width = 30;

  } else if (type === "payroll") {
    const ws = wb.addWorksheet("Payroll Detail");
    ws.views = [{ showGridLines: false }];
    logoHeader(ws, "Payroll Analysis", `${company} — ${period}`, 6);
    ["#", "Employee", "Role", "Department", "Gross Salary", "Net Salary"].forEach((h, i) => hdr(ws, 3, i + 1, h));
    const sorted = [...(extracted.employees || [])].sort((a, b) => b.gross_salary - a.gross_salary);
    sorted.forEach((e, i) => {
      const row = i + 4;
      const bg = i % 2 === 0 ? LIGHT : WHITE;
      cell(ws, row, 1, i + 1, { bg, align: "center" });
      cell(ws, row, 2, e.name, { bg });
      cell(ws, row, 3, e.role || "—", { bg });
      cell(ws, row, 4, e.department || "—", { bg });
      cell(ws, row, 5, e.gross_salary, { bg, numFmt: fmt });
      cell(ws, row, 6, e.net_salary ?? "—", { bg, numFmt: e.net_salary != null ? fmt : undefined });
      ws.getRow(row).height = 18;
    });
    const tr = sorted.length + 4;
    cell(ws, tr, 2, `TOTAL — ${extracted.headcount || sorted.length} employees`, { bold: true, bg: LIGHT_GREEN, color: NAVY });
    cell(ws, tr, 5, extracted.total_gross_calculated, { bold: true, bg: LIGHT_GREEN, numFmt: fmt });
    ws.getColumn(1).width = 6;
    ws.getColumn(2).width = 30;
    ws.getColumn(3).width = 25;
    ws.getColumn(4).width = 22;
    ws.getColumn(5).width = 20;
    ws.getColumn(6).width = 20;

    // Department summary
    if (extracted.employees?.some(e => e.department)) {
      const deptWs = wb.addWorksheet("By Department");
      deptWs.views = [{ showGridLines: false }];
      logoHeader(deptWs, "Payroll by Department", `${company} — ${period}`, 4);
      ["Department", "Headcount", "Total Gross", "Avg. Salary"].forEach((h, i) => hdr(deptWs, 3, i + 1, h));
      const deptMap = {};
      extracted.employees.forEach(e => {
        const d = e.department || "Unknown";
        if (!deptMap[d]) deptMap[d] = { count: 0, total: 0 };
        deptMap[d].count++;
        deptMap[d].total += Number(e.gross_salary) || 0;
      });
      const depts = Object.entries(deptMap).sort((a, b) => b[1].total - a[1].total);
      depts.forEach(([dept, { count, total }], i) => {
        const r = i + 4;
        const bg = i % 2 === 0 ? LIGHT : WHITE;
        cell(deptWs, r, 1, dept, { bg });
        cell(deptWs, r, 2, count, { bg, align: "center" });
        cell(deptWs, r, 3, total, { bg, numFmt: fmt });
        cell(deptWs, r, 4, count ? total / count : 0, { bg, numFmt: fmt });
        deptWs.getRow(r).height = 18;
      });
      deptWs.getColumn(1).width = 25;
      deptWs.getColumn(2).width = 14;
      deptWs.getColumn(3).width = 22;
      deptWs.getColumn(4).width = 22;
    }
  }

  // Red Flags sheet
  const rfData = analyzeRedFlags(extracted);
  const rfws = wb.addWorksheet("🚩 Red Flags");
  rfws.views = [{ showGridLines: false }];
  const gradeBgFull = "FF" + rfData.gradeColor;
  logoHeader(rfws, `Risk Assessment — Grade ${rfData.grade}`, `${extracted.company_name || "N/A"} | ${rfData.gradeLabel}`, 4);

  // Risk grade box
  rfws.mergeCells(3, 1, 4, 4);
  const gradeBox = rfws.getCell(3, 1);
  gradeBox.value = `Risk Grade: ${rfData.grade}  —  ${rfData.gradeLabel}  (Score: ${rfData.riskScore})`;
  gradeBox.font = { name: "Calibri", bold: true, size: 18, color: { argb: WHITE } };
  gradeBox.fill = { type: "pattern", pattern: "solid", fgColor: { argb: gradeBgFull } };
  gradeBox.alignment = { horizontal: "center", vertical: "middle" };
  rfws.getRow(3).height = 28;
  rfws.getRow(4).height = 28;

  rfws.getRow(5).height = 8;

  if (rfData.flags.length === 0) {
    rfws.mergeCells(6, 1, 6, 4);
    const noFlags = rfws.getCell(6, 1);
    noFlags.value = "✅ No red flags detected — document looks clean.";
    noFlags.font = { name: "Calibri", bold: true, size: 13, color: { argb: GREEN } };
    noFlags.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE8F5E9" } };
    noFlags.alignment = { horizontal: "center", vertical: "middle" };
    rfws.getRow(6).height = 30;
  } else {
    ["Severity", "Category", "Flag", "Details"].forEach((h, i) => hdr(rfws, 6, i + 1, h));
    const severityColor = { HIGH: RED, MEDIUM: "FFCC7700", LOW: "FF856404" };
    const severityBg   = { HIGH: "FFFDECEA", MEDIUM: "FFFFF3CD", LOW: "FFFFF9C4" };
    rfData.flags.forEach((flag, i) => {
      const r = 7 + i;
      const bg = severityBg[flag.severity] || LIGHT;
      const color = severityColor[flag.severity] || NAVY;
      cell(rfws, r, 1, flag.severity, { bold: true, color, bg, align: "center" });
      cell(rfws, r, 2, flag.category, { bg });
      cell(rfws, r, 3, flag.label, { bold: true, bg, color });
      cell(rfws, r, 4, flag.detail || "—", { bg });
      rfws.getRow(r).height = 20;
    });
  }
  rfws.getColumn(1).width = 12;
  rfws.getColumn(2).width = 22;
  rfws.getColumn(3).width = 45;
  rfws.getColumn(4).width = 45;

  // Validation Report — always last
  const vws = wb.addWorksheet("Validation Report");
  vws.views = [{ showGridLines: false }];
  logoHeader(vws, "Validation Report", "AI Extraction Quality Check — DataCrunch", 3);
  ["Check", "Result", "Details"].forEach((h, i) => hdr(vws, 3, i + 1, h));

  const notes = extracted.validation_notes || "";
  const hasIssues = notes.includes("⚠️");
  cell(vws, 4, 1, "Server-Side Validation");
  cell(vws, 4, 2, hasIssues ? "⚠️ Issues found" : "✅ All OK", { color: hasIssues ? RED : GREEN, bold: true });
  cell(vws, 4, 3, notes, { wrap: true });
  vws.getRow(4).height = 30;

  cell(vws, 5, 1, "AI Model");
  cell(vws, 5, 2, "Groq Llama 3.3 70B");
  cell(vws, 5, 3, "temperature=0 (deterministic)");

  cell(vws, 6, 1, "Document Type");
  cell(vws, 6, 2, extracted.document_type?.replace("_", " ") || "—");
  cell(vws, 6, 3, `Company: ${extracted.company_name || "N/A"} | Period: ${extracted.period || "N/A"}`);

  // Row counts — helps diagnose extraction issues
  const rowCount =
    extracted.employees?.length ||
    extracted.clients?.length ||
    (extracted.revenue?.items?.length || 0) + (extracted.expenses?.items?.length || 0);
  cell(vws, 7, 1, "Rows Extracted");
  cell(vws, 7, 2, rowCount || 0, { bold: true, color: rowCount ? GREEN : RED });
  cell(vws, 7, 3, rowCount
    ? `${rowCount} line items extracted successfully`
    : "⚠️ 0 rows extracted — PDF may be a scanned image or use an unsupported layout. Try a different PDF.");
  if (!rowCount) {
    vws.getCell(7, 3).font = { name: "Calibri", bold: true, color: { argb: RED }, size: 10 };
  }

  // Raw PDF text preview — helps diagnose extraction failures
  if (extracted._text_preview) {
    cell(vws, 8, 1, "PDF Text Preview");
    cell(vws, 8, 2, "(first 800 chars)");
    const preview = vws.getCell(8, 3);
    preview.value = extracted._text_preview;
    preview.font = { name: "Courier New", size: 8, color: { argb: "FF444444" } };
    preview.alignment = { wrapText: true, vertical: "top" };
    vws.getRow(8).height = 120;
  }

  vws.getColumn(1).width = 22;
  vws.getColumn(2).width = 22;
  vws.getColumn(3).width = 100;

  return wb.xlsx.writeBuffer();
}

// Comparison Excel: two financial statements side by side
export async function generateComparisonExcel(docA, docB, comparison) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "DataCrunch";
  wb.created = new Date();

  const currency = docA.currency || docB.currency || "EUR";
  const fmt = `#,##0.00 "${currency}"`;
  const pctFmt = '+0.0%;-0.0%;"—"';

  const ws = wb.addWorksheet("N vs N-1 Comparison");
  ws.views = [{ showGridLines: false }];

  const cols = 6;
  ws.mergeCells(1, 1, 1, cols);
  const title = ws.getCell(1, 1);
  title.value = "DataCrunch — Year-over-Year Comparison";
  title.font = { name: "Calibri", bold: true, size: 16, color: { argb: WHITE } };
  title.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
  title.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
  ws.getRow(1).height = 36;

  ws.mergeCells(2, 1, 2, cols);
  const sub = ws.getCell(2, 1);
  sub.value = `${docA.company_name || "N/A"} | ${docA.period || "N-1"} vs ${docB.period || "N"}`;
  sub.font = { name: "Calibri", size: 10, italic: true, color: { argb: NAVY } };
  sub.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEEF2F7" } };
  sub.alignment = { horizontal: "left", vertical: "middle", indent: 2 };
  ws.getRow(2).height = 20;

  ["Metric", docA.period || "N-1", docB.period || "N", "Change (€)", "Change (%)", "Trend"].forEach((h, i) => hdr(ws, 3, i + 1, h));

  let row = 4;
  const metrics = comparison.metrics || [];
  let lastSection = null;

  for (const m of metrics) {
    if (m.section && m.section !== lastSection) {
      sectionHeader(ws, row, cols, m.section.toUpperCase());
      lastSection = m.section;
      row++;
    }
    const bg = row % 2 === 0 ? LIGHT : WHITE;
    const change = m.b - m.a;
    const changePct = m.a !== 0 ? change / Math.abs(m.a) : null;
    const trend = changePct == null ? "—" : changePct > 0.05 ? "▲ Strong growth" : changePct > 0 ? "▲ Growth" : changePct < -0.05 ? "▼ Decline" : "▼ Slight decline";
    const trendColor = changePct == null ? "FF000000" : changePct > 0 ? GREEN : RED;

    cell(ws, row, 1, m.label, { bg, bold: m.bold });
    cell(ws, row, 2, m.a ?? "—", { bg, numFmt: m.a != null ? fmt : undefined });
    cell(ws, row, 3, m.b ?? "—", { bg, numFmt: m.b != null ? fmt : undefined });
    cell(ws, row, 4, m.a != null && m.b != null ? change : "—", { bg, numFmt: m.a != null && m.b != null ? fmt : undefined, color: change >= 0 ? GREEN : RED, bold: m.bold });
    cell(ws, row, 5, changePct, { bg, numFmt: changePct != null ? pctFmt : undefined });
    cell(ws, row, 6, trend, { bg, color: trendColor });
    ws.getRow(row).height = 18;
    row++;
  }

  ws.getColumn(1).width = 32;
  ws.getColumn(2).width = 20;
  ws.getColumn(3).width = 20;
  ws.getColumn(4).width = 20;
  ws.getColumn(5).width = 14;
  ws.getColumn(6).width = 20;

  return wb.xlsx.writeBuffer();
}
