import PptxGenJS from "pptxgenjs";

const NAVY = "1B2A4A";
const GREEN = "3DAA5C";
const RED = "C0392B";
const LIGHT = "F0F4F8";
const WHITE = "FFFFFF";

function fmtNum(n, currency = "EUR") {
  if (n == null || isNaN(n)) return "—";
  return new Intl.NumberFormat("fr-FR", { style: "currency", currency, maximumFractionDigits: 0 }).format(n);
}

function fmtPct(n) {
  if (n == null) return "—";
  return `${n.toFixed(1)}%`;
}

function addTitleSlide(pptx, company, period, docType) {
  const slide = pptx.addSlide();
  slide.background = { color: NAVY };

  // Top accent bar
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.4, h: "100%", fill: { color: GREEN } });

  // DataCrunch logo area
  slide.addText("DC", {
    x: 0.6, y: 0.4, w: 1.2, h: 1.2,
    fontSize: 36, bold: true, color: WHITE,
    align: "center", valign: "middle",
    fill: { color: GREEN }, shape: pptx.ShapeType.rect,
  });

  slide.addText("DataCrunch", {
    x: 2.0, y: 0.5, w: 7, h: 0.8,
    fontSize: 32, bold: true, color: WHITE,
  });

  slide.addText("M&A Due Diligence Platform", {
    x: 2.0, y: 1.2, w: 7, h: 0.4,
    fontSize: 14, color: "8FA3C0",
  });

  // Separator line
  slide.addShape(pptx.ShapeType.line, {
    x: 0.6, y: 2.0, w: 8.8, h: 0,
    line: { color: GREEN, width: 2 },
  });

  slide.addText(company, {
    x: 0.6, y: 2.3, w: 8.8, h: 0.8,
    fontSize: 28, bold: true, color: WHITE,
  });

  slide.addText(`Due Diligence Report — ${period}`, {
    x: 0.6, y: 3.1, w: 8.8, h: 0.5,
    fontSize: 16, color: "8FA3C0",
  });

  slide.addText(docType.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase()), {
    x: 0.6, y: 3.7, w: 8.8, h: 0.4,
    fontSize: 13, color: "6B8BAA",
  });

  slide.addText(`Generated by DataCrunch | ${new Date().toLocaleDateString("fr-FR")}`, {
    x: 0.6, y: 6.8, w: 8.8, h: 0.3,
    fontSize: 9, color: "4A6080",
  });
}

function addSlideHeader(slide, title, subtitle = "") {
  slide.addShape("rect", {
    x: 0, y: 0, w: "100%", h: 0.9,
    fill: { color: NAVY },
  });
  slide.addText(title, {
    x: 0.4, y: 0.05, w: 9.2, h: 0.5,
    fontSize: 20, bold: true, color: WHITE,
  });
  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.4, y: 0.55, w: 9.2, h: 0.3,
      fontSize: 10, color: "8FA3C0",
    });
  }
  // Green accent
  slide.addShape("rect", { x: 0, y: 0.9, w: "100%", h: 0.04, fill: { color: GREEN } });
}

function addKpiBox(slide, x, y, w, h, label, value, color = NAVY) {
  slide.addShape("rect", { x, y, w, h, fill: { color: LIGHT }, line: { color: "DEE2E6", width: 0.5 } });
  slide.addText(label, { x, y: y + 0.05, w, h: 0.3, fontSize: 9, bold: true, color: "6B7A99", align: "center" });
  slide.addText(value, { x, y: y + 0.35, w, h: 0.55, fontSize: 16, bold: true, color, align: "center" });
}

function addTableSlide(pptx, title, subtitle, headers, rows, colWidths) {
  const slide = pptx.addSlide();
  addSlideHeader(slide, title, subtitle);

  const tableData = [
    headers.map(h => ({
      text: h,
      options: { bold: true, color: WHITE, fill: NAVY, align: "center", fontSize: 10 },
    })),
    ...rows.map((row, ri) =>
      row.map((val, ci) => ({
        text: String(val ?? "—"),
        options: {
          fontSize: 9,
          fill: ri % 2 === 0 ? LIGHT : WHITE,
          align: ci === 0 ? "left" : "right",
          color: "3D4B66",
        },
      }))
    ),
  ];

  slide.addTable(tableData, {
    x: 0.3,
    y: 1.1,
    w: 9.4,
    rowH: 0.3,
    colW: colWidths,
    border: { type: "solid", color: "DEE2E6", pt: 0.5 },
  });

  return slide;
}

export async function generatePowerPoint(extracted) {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.title = "DataCrunch Due Diligence Report";
  pptx.subject = "M&A Financial Analysis";
  pptx.author = "DataCrunch";

  const company = extracted.company_name || "N/A";
  const period = extracted.period || "N/A";
  const currency = extracted.currency || "EUR";
  const type = extracted.document_type;

  // Slide 1: Title
  addTitleSlide(pptx, company, period, type);

  if (type === "financial_statement") {
    const revenue = extracted.revenue?.total_calculated;
    const expenses = extracted.expenses?.total_calculated;
    const ebitda = extracted.ebitda;
    const netIncome = extracted.net_income;
    const assets = extracted.assets?.total_calculated;
    const liabilities = extracted.liabilities?.total_calculated;
    const equity = assets != null && liabilities != null ? assets - liabilities : null;
    const ebitdaMargin = revenue && ebitda ? ((ebitda / revenue) * 100).toFixed(1) + "%" : "N/A";
    const netMargin = revenue && netIncome ? ((netIncome / revenue) * 100).toFixed(1) + "%" : "N/A";

    // Slide 2: Executive Summary KPIs
    const slide2 = pptx.addSlide();
    addSlideHeader(slide2, "Executive Summary", `${company} — ${period}`);

    const kpis = [
      { label: "Total Revenue", value: fmtNum(revenue, currency), color: NAVY },
      { label: "Total Expenses", value: fmtNum(expenses, currency), color: NAVY },
      { label: "EBITDA", value: fmtNum(ebitda, currency), color: GREEN },
      { label: "EBITDA Margin", value: ebitdaMargin, color: GREEN },
      { label: "Net Income", value: fmtNum(netIncome, currency), color: GREEN },
      { label: "Net Margin", value: netMargin, color: GREEN },
      { label: "Total Assets", value: fmtNum(assets, currency), color: NAVY },
      { label: "Net Equity", value: fmtNum(equity, currency), color: NAVY },
    ];

    const kpiW = 2.3, kpiH = 1.0, kpiGap = 0.1;
    kpis.forEach((kpi, i) => {
      const col = i % 4;
      const row = Math.floor(i / 4);
      addKpiBox(slide2,
        0.3 + col * (kpiW + kpiGap),
        1.1 + row * (kpiH + kpiGap),
        kpiW, kpiH,
        kpi.label, kpi.value, kpi.color
      );
    });

    // Validation badge
    const hasIssues = extracted.validation_notes?.includes("⚠️");
    slide2.addShape("rect", {
      x: 0.3, y: 3.5, w: 9.4, h: 0.5,
      fill: { color: hasIssues ? "FDECEA" : "E8F5E9" },
      line: { color: hasIssues ? RED : GREEN, width: 1 },
    });
    slide2.addText(hasIssues ? "⚠️ Validation issues detected — check Validation Report" : "✅ All financial totals validated server-side", {
      x: 0.3, y: 3.5, w: 9.4, h: 0.5,
      fontSize: 11, bold: true,
      color: hasIssues ? RED : GREEN,
      align: "center", valign: "middle",
    });

    // Slide 3: Revenue
    if (extracted.revenue?.items?.length) {
      const rows = extracted.revenue.items
        .sort((a, b) => b.amount - a.amount)
        .slice(0, 15)
        .map(item => [
          item.label,
          fmtNum(item.amount, currency),
          revenue ? fmtPct((item.amount / revenue) * 100) : "—",
        ]);
      rows.push(["TOTAL", fmtNum(revenue, currency), "100%"]);
      addTableSlide(pptx, "Revenue Breakdown", `${company} — ${period}`,
        ["Revenue Item", "Amount", "% of Total"], rows, [5.5, 2.2, 1.7]);
    }

    // Slide 4: Expenses
    if (extracted.expenses?.items?.length) {
      const rows = extracted.expenses.items
        .sort((a, b) => b.amount - a.amount)
        .slice(0, 15)
        .map(item => [
          item.label,
          fmtNum(item.amount, currency),
          expenses ? fmtPct((item.amount / expenses) * 100) : "—",
        ]);
      rows.push(["TOTAL", fmtNum(expenses, currency), "100%"]);
      addTableSlide(pptx, "Expense Breakdown", `${company} — ${period}`,
        ["Expense Item", "Amount", "% of Total"], rows, [5.5, 2.2, 1.7]);
    }

    // Slide 5: Balance Sheet
    if (extracted.assets?.items?.length || extracted.liabilities?.items?.length) {
      const slide5 = pptx.addSlide();
      addSlideHeader(slide5, "Balance Sheet", `${company} — ${period}`);

      const assetRows = (extracted.assets?.items || []).map(item => [item.label, fmtNum(item.amount, currency)]);
      const liabRows = (extracted.liabilities?.items || []).map(item => [item.label, fmtNum(item.amount, currency)]);

      if (assetRows.length) {
        slide5.addText("ASSETS", { x: 0.3, y: 1.1, w: 4.5, h: 0.3, fontSize: 11, bold: true, color: NAVY });
        assetRows.forEach(([label, val], i) => {
          slide5.addText(label, { x: 0.3, y: 1.45 + i * 0.28, w: 3.0, h: 0.25, fontSize: 9, color: "3D4B66" });
          slide5.addText(val, { x: 3.3, y: 1.45 + i * 0.28, w: 1.5, h: 0.25, fontSize: 9, align: "right", color: "3D4B66" });
        });
        slide5.addText("Total Assets", { x: 0.3, y: 1.45 + assetRows.length * 0.28, w: 3.0, h: 0.28, fontSize: 10, bold: true, color: NAVY });
        slide5.addText(fmtNum(assets, currency), { x: 3.3, y: 1.45 + assetRows.length * 0.28, w: 1.5, h: 0.28, fontSize: 10, bold: true, align: "right", color: NAVY });
      }

      if (liabRows.length) {
        slide5.addText("LIABILITIES", { x: 5.2, y: 1.1, w: 4.5, h: 0.3, fontSize: 11, bold: true, color: RED });
        liabRows.forEach(([label, val], i) => {
          slide5.addText(label, { x: 5.2, y: 1.45 + i * 0.28, w: 3.0, h: 0.25, fontSize: 9, color: "3D4B66" });
          slide5.addText(val, { x: 8.2, y: 1.45 + i * 0.28, w: 1.5, h: 0.25, fontSize: 9, align: "right", color: "3D4B66" });
        });
        slide5.addText("Total Liabilities", { x: 5.2, y: 1.45 + liabRows.length * 0.28, w: 3.0, h: 0.28, fontSize: 10, bold: true, color: RED });
        slide5.addText(fmtNum(liabilities, currency), { x: 8.2, y: 1.45 + liabRows.length * 0.28, w: 1.5, h: 0.28, fontSize: 10, bold: true, align: "right", color: RED });
      }

      if (equity != null) {
        slide5.addShape("rect", { x: 0.3, y: 5.8, w: 9.4, h: 0.45, fill: { color: NAVY } });
        slide5.addText(`Net Equity (Assets − Liabilities): ${fmtNum(equity, currency)}`, {
          x: 0.3, y: 5.8, w: 9.4, h: 0.45,
          fontSize: 12, bold: true, color: WHITE, align: "center", valign: "middle",
        });
      }
    }

  } else if (type === "revenue_list") {
    const total = extracted.total_calculated || 0;
    const clients = [...(extracted.clients || [])].sort((a, b) => b.revenue - a.revenue);

    // Slide 2: Summary KPIs
    const slide2 = pptx.addSlide();
    addSlideHeader(slide2, "Revenue Summary", `${company} — ${period}`);
    const top5 = clients.slice(0, 5).reduce((s, c) => s + c.revenue, 0);
    const top5Pct = total ? (top5 / total * 100).toFixed(1) + "%" : "N/A";
    [
      { label: "Total Revenue", value: fmtNum(total, currency), color: NAVY },
      { label: "# Clients", value: String(clients.length), color: NAVY },
      { label: "Top 5 Concentration", value: top5Pct, color: top5 / total > 0.6 ? RED : GREEN },
      { label: "Avg. Revenue / Client", value: fmtNum(clients.length ? total / clients.length : 0, currency), color: NAVY },
    ].forEach((kpi, i) => addKpiBox(slide2, 0.3 + i * 2.45, 1.2, 2.25, 1.0, kpi.label, kpi.value, kpi.color));

    // Slide 3: Client table
    const rows = clients.slice(0, 20).map((c, i) => [
      i + 1,
      c.name,
      fmtNum(c.revenue, currency),
      fmtPct((c.revenue / (total || 1)) * 100),
      (c.revenue / (total || 1)) * 100 > 30 ? "🔴 High" : "🟢 Low",
    ]);
    addTableSlide(pptx, "Revenue per Client", `${company} — ${period}`,
      ["#", "Client", "Revenue", "% Total", "Risk"], rows, [0.5, 4.5, 2.0, 1.2, 1.2]);

  } else if (type === "payroll") {
    const total = extracted.total_gross_calculated || 0;
    const employees = [...(extracted.employees || [])].sort((a, b) => b.gross_salary - a.gross_salary);
    const headcount = extracted.headcount || employees.length;

    // Slide 2: Payroll KPIs
    const slide2 = pptx.addSlide();
    addSlideHeader(slide2, "Payroll Summary", `${company} — ${period}`);
    [
      { label: "Total Gross Payroll", value: fmtNum(total, currency), color: NAVY },
      { label: "Headcount", value: String(headcount), color: NAVY },
      { label: "Avg. Gross Salary", value: fmtNum(headcount ? total / headcount : 0, currency), color: GREEN },
      { label: "Highest Salary", value: fmtNum(employees[0]?.gross_salary, currency), color: NAVY },
    ].forEach((kpi, i) => addKpiBox(slide2, 0.3 + i * 2.45, 1.2, 2.25, 1.0, kpi.label, kpi.value, kpi.color));

    // Slide 3: Employee table (top 20)
    const rows = employees.slice(0, 20).map((e, i) => [
      i + 1, e.name, e.role || "—", e.department || "—",
      fmtNum(e.gross_salary, currency),
    ]);
    addTableSlide(pptx, "Payroll Detail", `${company} — ${period}`,
      ["#", "Employee", "Role", "Department", "Gross Salary"], rows, [0.4, 2.8, 2.2, 2.0, 2.0]);
  }

  // Last slide: Validation / Disclaimer
  const lastSlide = pptx.addSlide();
  addSlideHeader(lastSlide, "Validation Report", "AI Extraction Quality Check");
  const hasIssues = extracted.validation_notes?.includes("⚠️");
  lastSlide.addShape("rect", {
    x: 0.3, y: 1.2, w: 9.4, h: 0.7,
    fill: { color: hasIssues ? "FDECEA" : "E8F5E9" },
    line: { color: hasIssues ? RED : GREEN, width: 1 },
  });
  lastSlide.addText(hasIssues ? "⚠️ Validation Issues Detected" : "✅ All Totals Validated", {
    x: 0.3, y: 1.2, w: 9.4, h: 0.7,
    fontSize: 18, bold: true, color: hasIssues ? RED : GREEN,
    align: "center", valign: "middle",
  });
  lastSlide.addText(extracted.validation_notes || "", {
    x: 0.3, y: 2.1, w: 9.4, h: 1.0,
    fontSize: 10, color: "3D4B66", wrap: true,
  });
  lastSlide.addText([
    { text: "Model: ", options: { bold: true } },
    { text: "Groq Llama 3.3 70B, temperature=0 (deterministic)\n" },
    { text: "Validation: ", options: { bold: true } },
    { text: "All totals calculated server-side — AI only extracts raw values\n" },
    { text: "Disclaimer: ", options: { bold: true } },
    { text: "This report is generated by AI and should be reviewed by a qualified financial professional before use in any transaction." },
  ], {
    x: 0.3, y: 3.3, w: 9.4, h: 2.0,
    fontSize: 10, color: "6B7A99", wrap: true,
  });

  return pptx.write({ outputType: "nodebuffer" });
}
